import { NextRequest } from 'next/server';
import { authenticate } from '@/core/auth';
import { projectService } from '@/core/project/project-service';
import { versionService } from '@/core/project/version-service';
import { handleError } from '@/core/errors';
import { successResponse, generateRequestId } from '@/utils/response';
import { Octokit } from '@octokit/rest';

export async function POST(
  req: NextRequest,
  { params }: { params: Promise<{ projectId: string }> }
) {
  const requestId = generateRequestId();

  try {
    const user = authenticate(req);
    const { projectId } = await params;
    
    const body = await req.json();
    const { token, repoName } = body;

    if (!token || !repoName) {
      throw new Error('Token and repoName are required');
    }

    const project = await projectService.getProject(user.userId, projectId);
    const versionData = await versionService.getVersionFiles(projectId, project.currentVersion);

    const octokit = new Octokit({ auth: token });

    // 1. Get authenticated user
    const { data: currentUser } = await octokit.users.getAuthenticated();
    const owner = currentUser.login;

    // 2. Create Repository
    await octokit.repos.createForAuthenticatedUser({
      name: repoName,
      description: `Generated by BuildBot: ${project.prompt}`,
      private: false,
      auto_init: true, // Creates initial commit with README so we can get a base tree
    });

    // 3. Get base tree SHA from main branch
    // Wait a brief moment for the repo to be fully initialized on GitHub's end
    await new Promise(resolve => setTimeout(resolve, 2000));
    
    const { data: refData } = await octokit.git.getRef({
      owner,
      repo: repoName,
      ref: 'heads/main',
    }).catch(async () => {
      // Fallback to master if main doesn't exist
      return await octokit.git.getRef({
        owner,
        repo: repoName,
        ref: 'heads/master',
      });
    });

    const commitSha = refData.object.sha;
    const { data: commitData } = await octokit.git.getCommit({
      owner,
      repo: repoName,
      commit_sha: commitSha,
    });
    const baseTreeSha = commitData.tree.sha;

    // 4. Create blobs and tree
    const tree = await Promise.all(
      versionData.files.map(async (f: { path: string; content: string }) => {
        const { data: blobData } = await octokit.git.createBlob({
          owner,
          repo: repoName,
          content: f.content,
          encoding: 'utf-8',
        });
        return {
          path: f.path,
          mode: '100644' as const,
          type: 'blob' as const,
          sha: blobData.sha,
        };
      })
    );

    const { data: treeData } = await octokit.git.createTree({
      owner,
      repo: repoName,
      base_tree: baseTreeSha,
      tree,
    });

    // 5. Create new commit
    const { data: newCommitData } = await octokit.git.createCommit({
      owner,
      repo: repoName,
      message: 'Initial commit by BuildBot',
      tree: treeData.sha,
      parents: [commitSha],
    });

    // 6. Update reference
    await octokit.git.updateRef({
      owner,
      repo: repoName,
      ref: refData.ref.replace('refs/', ''),
      sha: newCommitData.sha,
    });

    return successResponse({ 
      success: true, 
      url: `https://github.com/${owner}/${repoName}` 
    }, 200, { requestId });
  } catch (error) {
    return handleError(error, requestId);
  }
}
